### ISSUE TITLE
Multi-channel simultaneous recording

### ISSUE THREAD

**Issue by leewujung** [aidanjohnson/dt7816#7]
- [x] Program to allow fixed time recording from multiple channels (in parallel to #11)
- [x] Allow user to select channels
- [x] Establish testing requirements for checking multi-channel simultaneous recording (linked to #5)
- [x] Document indicator patterns for recording channels (linked to #4)

**Comment by aidanjohnson** [comment]
For help on the multi-channel mask: [bitwise shifts](https://www.alanzucconi.com/2015/07/26/enum-flags-and-bitwise-operators/)

**Comment by aidanjohnson** [comment]
UPDATE (2018-07-03): the method described above (^) has been implemented for the channel mask.

**Comment by aidanjohnson** [comment]
@funnyabc and I were discussing activating sampling for sunrise and sunset. We were exploring two ideas:

1. Light detecting sensor.
2. Calculated times, or even a lookup table of time calculated by the Navy.

If we go with this idea the design will have to be low power, reliable, and offline. For 1. the sensor (either a photo, UV, or IR-sensor) would be connected to the board via the GPIO pins. @funnyabc  was willing to write the driver and program for deciding if it is sunrise or sunset. This will require calibration for the deployment site. He was also thinking a moving window average would serve as the measured intensity value to compare  to a calibrated threshold. He found these sensors: [Adafruit](https://learn.adafruit.com/tsl2561) and [UUGear](http://www.uugear.com/product/uugear-light-sensor-module-4-wire-with-both-digital-and-analog-output/).

For 2. this would be a more simple implementation. This [database](http://aa.usno.navy.mil/data/docs/RS_OneYear.php) from the Navy would be useful. It has an API so we can construct our own table such that it has a format to our liking. Since the local time can now be saved to the hardware clock, the board can wait until sunset occurs for a given day and then turn off the next day at sunrise. 

We were unsure which would be more energy efficient and easier to implement.

**Comment by leewujung** [comment]
Let's go with option 2 because it is straightforward and does not require additional calibration. It's a good idea to start recording ahead of sunset (depending on how you define it) since we don't want to miss the emergence. Many factors can affect light levels and it gets messy.

It is a good idea to have light sensors though for environmental monitoring so @funnyabc let's make a note of that in the [project board](https://github.com/aidanjohnson/dt7816/projects/1).

Also this is actually #11. Do you guys want to do this (#7) and #11 in parallel?

**Comment by aidanjohnson** [comment]
I like the idea of working on them in parallel.

**Comment by aidanjohnson** [comment]
Efforts related to testing and the requirements transferred to #11
